### ISSUE TITLE
Is it possible to use StyleCopPlus with StyleCop Analyzers?

### ISSUE THREAD

**Issue by KyleXie** [sergey-rybalkin/StyleCopPlus.Analyzers#1]
Currently I use [StyleCop.CLI](https://github.com/rookxx/StyleCopAnalyzers.CLI) to do style cop scan on command lines, is there any way I can integrate  StyleCopPlus into the CLI tool?

Thanks for your time.

**Comment by sergey-rybalkin** [comment]
@KyleXie, if you add StyleCopPlus as a NuGet package to your solution/project then it will run as part of your build process, including command line builds with MSBuild. For now that is the only way to run them from command line I can think of.

**Comment by KyleXie** [comment]
@sergey-rybalkin Thanks for your reply. When I try to add StyleCopPlus as a NuGet package, I can't find it on https://www.nuget.org/, did you published it to https://www.nuget.org/?

**Comment by KyleXie** [comment]
I figured out you have a nupkg file, but seems the nuget package is empty after installed, you can see from the screenshot, there're no any dll files inside the package.

![image](https://user-images.githubusercontent.com/2870241/67259076-9579cc00-f4c6-11e9-938e-c581c32fa715.png)

**Comment by sergey-rybalkin** [comment]
> I figured out you have a nupkg file, but seems the nuget package is empty after installed, you can see from the screenshot, there're no any dll files inside the package.

True, seems like I didn't have instructions for this in my project file. Just pushed a commit with a fix for this.



> did you published it to https://www.nuget.org/?

No, it's just not stable and popular enough:-) I think the best way would be to use internal nuget share or server.

**Comment by sergey-rybalkin** [comment]
Just published version for Visual Studio 2022 on [nuget](https://www.nuget.org/packages/StyleCopPlus/3.0.0)
